import { PORTAGE_ITEMS } from "./portage-data.js";
const ENDPOINT="https://rvgcniaowzmsudzliozf.supabase.co/functions/v1/psico-scale-response";
const token=new URLSearchParams(location.search).get("token");
const $=id=>document.getElementById(id), loading=$("loading"),app=$("app"),errorBox=$("error"),identity=$("identityForm"),questionBox=$("questionBox"),done=$("done"),bar=$("bar"),progress=$("progress"),counter=$("counter"),area=$("area"),question=$("question"),options=$("options"),back=$("back"),next=$("next"),finish=$("finish"),ageTabs=$("ageTabs"),saveState=$("saveState");
let items=[],answers={},index=0,scaleName="",currentAge="",data={};
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const ages=["0 a 1 ano","1 a 2 anos","2 a 3 anos","3 a 4 anos","4 a 5 anos","5 a 6 anos"];
function showError(t){loading.hidden=true;app.hidden=true;errorBox.hidden=false;errorBox.innerHTML="<strong>Não foi possível abrir esta avaliação.</strong><br>"+esc(t)}
async function api(method,body){const r=await fetch(ENDPOINT+"?token="+encodeURIComponent(token),{method,headers:{"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erro");return d}
async function start(){if(!token)return showError("O link da avaliação está incompleto.");try{data=await api("GET");scaleName=data.scale?.name||"Avaliação";currentAge=data.age_range||"";document.title=scaleName+" | Espaço Graça";$("scaleName").textContent=scaleName;$("intro").textContent=data.scale?.description||"Responda conforme sua observação da criança.";if(data.patient?.full_name){$("patientName").textContent=data.patient.full_name;$("patientConfirm").value=data.patient_confirm_name||"";$("patientPhone").value=data.patient_confirm_phone||""}$("respondentName").value=data.respondent_name||"";$("respondentPhone").value=data.respondent_phone||"";const saved=data.response_data||{};if(saved.answers)answers=saved.answers;items=scaleName.toLowerCase().includes("portage")?PORTAGE_ITEMS.filter(x=>!data.age_range||x.age_range===data.age_range):(Array.isArray(data.scale?.items)?data.scale.items:[]);if(!items.length)throw new Error("Esta escala ainda não possui itens configurados.");loading.hidden=true;app.hidden=false;renderAgeTabs();render();}catch(e){showError(e.message)}}
function renderAgeTabs(){if(scaleName.toLowerCase().includes("portage")&&!currentAge){ageTabs.innerHTML="<div class=\"age-tab active\"><strong>Faixa etária não informada</strong><small>Crie uma nova aplicação escolhendo a idade.</small></div>";return}ageTabs.innerHTML=scaleName.toLowerCase().includes("portage")?'<div class="age-tab active" style="cursor:default"><strong>'+esc(currentAge)+'</strong><small>Faixa selecionada pela profissional</small></div>':ages.map(a=>{const n=items.filter(x=>x.age_range===a).length;return '<button type="button" class="age-tab '+(a===currentAge?"active":"")+'" data-age="'+esc(a)+'"><strong>'+esc(a)+'</strong><small>'+n+" habilidades</small></button>"}).join("");ageTabs.querySelectorAll("button").forEach(b=>b.onclick=()=>{currentAge=b.dataset.age;index=0;renderAgeTabs();render()})}
function ageItems(){return items.filter(x=>x.age_range===currentAge)}
function render(){const list=ageItems();if(!list.length){question.textContent="Nenhuma habilidade cadastrada nesta faixa.";return}const total=list.length,pct=Math.round((index/total)*100),it=list[index],key=it.number,chosen=answers[key];area.textContent=(it.area||"Avaliação")+" · "+currentAge;question.textContent=it.question;counter.textContent=(index+1)+" de "+total;progress.textContent=pct+"%";bar.style.width=Math.max(3,pct)+"%";options.innerHTML=(it.options||["S","N","AV"]).map(o=>{const labels={S:"Sim",N:"Não",AV:"Às vezes"};return '<button type="button" class="answer '+(chosen===o?"selected":"")+'" data-value="'+esc(o)+'"><span class="dot">'+esc(o)+'</span><span><strong>'+labels[o]+'</strong><small>'+({S:"Alcançou",N:"Ainda não alcançou",AV:"Às vezes"}[o])+'</small></span></button>'}).join("");options.querySelectorAll(".answer").forEach(b=>b.onclick=()=>{answers[key]=b.dataset.value;saveProgress();render()});back.disabled=index===0;next.hidden=index===total-1;finish.hidden=!(index===total-1);next.disabled=chosen==null;finish.disabled=Object.keys(answers).length!==items.length;saveState.textContent=Object.keys(answers).length+" de "+items.length+" habilidades respondidas. As respostas são salvas automaticamente."}
async function saveProgress(){const identityData={patient_confirm_name:$("patientConfirm").value.trim(),patient_confirm_phone:$("patientPhone").value.trim(),respondent_name:$("respondentName").value.trim(),respondent_phone:$("respondentPhone").value.trim(),response_data:{answers}};if(!identityData.patient_confirm_name||!identityData.patient_confirm_phone||!identityData.respondent_name||!identityData.respondent_phone)return;saveState.textContent="Salvando...";try{await api("POST",{mode:"save",...identityData});saveState.textContent="✓ Salvo automaticamente";}catch(e){saveState.textContent="Não foi possível salvar agora."}}
$("identityForm").onsubmit=e=>{e.preventDefault();identity.hidden=true;questionBox.hidden=false;saveProgress();render()};
back.onclick=()=>{if(index>0){index--;render()}};
next.onclick=()=>{if(answers[ageItems()[index].number]!=null&&index<ageItems().length-1){index++;render()}};
finish.onclick=async()=>{finish.disabled=true;finish.textContent="Enviando...";const response_data=items.map(it=>({number:it.number,area:it.area,age_range:it.age_range,question:it.question,answer:answers[it.number]??null}));const byAge={};for(const r of response_data){byAge[r.age_range]??={S:0,N:0,AV:0,total:0};if(r.answer)byAge[r.age_range][r.answer]++;byAge[r.age_range].total++}try{await api("POST",{mode:"finalize",patient_confirm_name:$("patientConfirm").value.trim(),patient_confirm_phone:$("patientPhone").value.trim(),respondent_name:$("respondentName").value.trim(),respondent_phone:$("respondentPhone").value.trim(),response_data,result_summary:byAge,notes:"Aplicação online"});questionBox.hidden=true;done.hidden=false}catch(e){finish.disabled=false;finish.textContent="Finalizar avaliação";alert(e.message)}};
start();